### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by MannyFay** [beeender/Comrade#34]
I'm new to Neovim and the installation workflow of Comrade in Neovim is very complex :/

I run into this error:
```
Error detected while processing /Volumes/Users/manny/.local/share/nvim/site/pack/packer/start/Comrade/plugin/comrade.vim[27]..function provider#python3#Call:
line   18:
Error invoking 'python_execute_file' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "/Volumes/Users/manny/.local/share/nvim/site/pack/packer/start/Comrade/plugin/init.py", line 77, in <module>
    init()
  File "/Volumes/Users/manny/.local/share/nvim/site/pack/packer/start/Comrade/plugin/init.py", line 71, in init
    pid_file.write(addr + "\n")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I'm on macOS Ventura with the following Neovim/Packer setup:
~/.config/nvim/lua/user/core/plugins.lua:
```
use({
  'Shougo/deoplete.nvim',
   run = ':UpdateRemotePlugins',
  requires = {
    'roxma/nvim-yarp',
    'roxma/vim-hug-neovim-rpc',
    run = 'pip install -r requirements.txt'
  },
  config = function()
    require('user.plugin_options.deoplete')
  end,
})

use({
  'beeender/Comrade'
})
```
~/.config/nvim/lua/user/plugin_options/deoplete.lua:
```
vim.g['deoplete#enable_at_startup'] = 1
vim.fn['python3_host_prog'] = '/usr/bin/python3'
```

I don't know how to help myself - Can anybody help me to solve this?

**Comment by Glyphack** [comment]
The issue you have is fixed in this [PR](https://github.com/beeender/Comrade/pull/33), but it's not merged. What you can do is to find the local files of this plugin installed in your path by packer and edit them

**Comment by MannyFay** [comment]
... omg ... dude ... seriously :'D

I wait, till it is merged. Is it merged already?

**Comment by Glyphack** [comment]
It's not merged but the project hasn't been updated for a long time, I don't expect it to be merged soon. But it should be easy to edit that one line yourself, another solution is to manually set the value of env variable `NVIM_LISTEN_ADDRESS` to `$NVIM`.
